apiVersion: v2
name: helm-chart-dependency
description: A Helm chart for Kubernetes
dependencies:
- name: kafka
  version: "19.1.x"
  repository: "https://charts.bitnami.com/bitnami"
- name: prometheus
  version: "17.0.x"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: grafana
  version: "6.44.x"
  repository: "https://grafana.github.io/helm-charts"
- name: elasticsearch
  version: "7.17.x"
  repository: "https://helm.elastic.co"
  # - name: metrics-server
  #   repository: https://charts.bitnami.com/bitnami
  #   version: ~6.2.3
  # - name: efk
  #   repository: https://helm.cryptexlabs.com
  #   version: ~7.17.3
  # # - name: fluentd
  # #   repository: https://charts.bitnami.com/bitnami
  # #   version: ~19.5.2
  # - name: grafana
  #   repository: https://charts.bitnami.com/bitnami
  #   version: ~8.2.18
  # # - name: kibana
  # #   repository: https://charts.bitnami.com/bitnami
  # #   version: ~19.5.2
  # - name: kube-prometheus
  #   repository: https://charts.bitnami.com/bitnami
  #   version: ~8.2.0
  # # - name: zookeeper
  # #   repository: https://charts.bitnami.com/bitnami
  # #   version: ~10.2.5
  # - name: kafka
  #   repository: https://charts.bitnami.com/bitnami
  #   version: ~19.1.3

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

maintainers:
  - name: Vinit Harsora
    email: harsora.v@northeastern.edu
  - name: Harshal Jaiswal
    email: jaiswal.ha@northeastern.edu
  - name: Shrawani Karpe
    email: karpe.s@northeastern.edu