apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cert-prod
  namespace: istio-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certificate.email }}
    privateKeySecretRef:
      name: letsencrypt-cert-prod
    solvers:
    - http01:
        ingress:
          class: istio