apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart-dependency.fullname" . }}
  labels:
    {{- include "helm-chart-dependency.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3030
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart-dependency.selectorLabels" . | nindent 4 }}
